lab_1/urls.py
from django.conf.urls import url
from .views import home

# url for app
urlpatterns = [
    url(r'^$',home, name= 'home'),
]

lab_2/urls.py
from django.urls import path

from .views import hal1
from .views import about
from .views import project
from .views import activity
from .views import contact
from .views import galery
from .views import jadwal
from .views import tambahJadwal
from .views import hapusJadwal
from .views import pilih

app_name = 'lab_2'
# url for app
urlpatterns = [
    path('',hal1, name= 'hal1'),
    path('about/',about, name= 'about'),
    path('project/',project, name= 'project'),
    path('activity/',activity, name= 'activity'),
    path('contact/',contact, name= 'contact'),
    path('galery/',galery, name= 'galery'),
    path('jadwal/',jadwal,name ='jadwal'),
    path('tambahJadwal/',tambahJadwal, name ='tambahJadwal'),
    path('pilih/<jadwal_id>',pilih, name='pilih'),
    path('hapusJadwal/',hapusJadwal,name='hapusJadwal'),

]

myweb/urls.py
from django.urls import path, include
from django.contrib import admin
# import lab_1.urls as lab_1
# import lab_2.urls as lab_2
import lab_2.urls as lab_2
from django.conf import settings
from django.conf.urls.static import static


# url for app
urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^', include(lab_1, namespace='lab_1')),
    # path('', include(lab_2, namespace='lab_2')),
    path('', include(lab_2, namespace='lab_2')),
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nmKegiatan = models.CharField(max_length=40)
    tanggal = models.DateField()
    tempat = models.CharField(max_length=40)
    waktu = models.TimeField()
    kategori = models.CharField(max_length=40)
    pilihan = models.BooleanField(default = False)

    def __str__(self):
        return self.nmKegiatan

lab_2/forms.py
from django import forms

class Formulir(forms.Form):
    nmKegiatan = forms.CharField(max_length=40,widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Enter your Activity e.g. Play Football'}))
    tanggal = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control', 'placeholder':'','type':'date'}))
    tempat = forms.CharField(max_length=40, widget= forms.TextInput(attrs={'class':'form-control', 'placeholder': 'Enter the Location e.g. Arena Futsal'}))
    waktu = forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control','type':'time'}))
    kategori = forms.CharField(max_length=40,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the Category e.g. UKOR'}))

lab_1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'story1.html')

lab_2/views.py
from django.shortcuts import render, redirect
from .forms import Formulir
from .models import Jadwal
from django.views.decorators.http import require_POST

# Create your views here.
def hal1(request):
    return render(request,'story1.html')

def about(request):
    return render(request,'about.html')

def project(request):
    return render(request,'project.html')

def activity(request):
    return render(request,'activity.html')

def contact(request):
    return render(request,'contact.html')

def galery(request):
    return render(request,'galery.html')

def jadwal(request):
    jadwal_list = Jadwal.objects.order_by('tanggal')
    form = Formulir()
    context = {'jadwal_list' : jadwal_list, 'form': form}
    return render(request,'jadwal.html',context)

@require_POST
def tambahJadwal(request):
	form = Formulir(request.POST)
	
	if form.is_valid():
		jadwalBaru = Jadwal(nmKegiatan=request.POST['nmKegiatan'],tanggal=request.POST['tanggal'],tempat=request.POST['tempat'],waktu=request.POST['waktu'],kategori=request.POST['kategori'])
		jadwalBaru.save()

	return redirect('lab_2:jadwal')

def pilih(request, jadwal_id):
	jadwal = Jadwal.objects.get(pk = jadwal_id)

	if jadwal.pilihan == False:
		jadwal.pilihan = True
	else :
		jadwal.pilihan = False
	
	jadwal.save()

	return redirect('lab_2:jadwal')

def hapusJadwal(request):
	Jadwal.objects.filter(pilihan__exact = True).delete()

	return redirect('lab_2:jadwal')

# def tambahJadwal(request):
#     form = Formulir(request.POST)
#     newJadwal = Jadwal(nmKegiatan = request.POST['nmKegiatan'],tanggal = request.POST['tanggal'],tempat=request.POST['tempat'],
#                         waktu = request.POST['waktu'],kategori=request.POST['kategori'])
#     newJadwal.save()
#     return redirect('lab_2:jadwal')

# def hapusJadwal(request, jadwal_id):
    
#     Jadwal.objects.filter(id=jadwal_id).delete()
    
#     return redirect('lab_2:jadwal')

lab_2/templates/about.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="bootstrap-4.3.1-dist/css/bootstrap.css"> -->
    <link rel="stylesheet" href="{% static 'static2/css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <title>About</title>
</head>
<body id="about">
    <nav class="navbar">
        <div class="boxx">
            <a href="{% url 'lab_2:hal1' %}"><div id="box2"></div><div id="box">Jr.</div></a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'lab_2:about' %}">About</a></li>
            <li><a href="{% url 'lab_2:project' %}">Project</a></li>
            <li><a href="{% url 'lab_2:activity' %}">Activities</a></li>
            <li><a href="{% url 'lab_2:contact' %}">Contact</a></li>
        </ul>
        <div class="slide">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div class="partitle">
        <div class="partitle partitleloc partitlelocation">About</div>
        <div class="partitle partitleloc partitlelocation2">Education</div>
        <div class="partitle partitleloc partitlelocation3">Skills</div>
        <div class="partitle text textname">Fajar Anugerah Subekti</div>
        <div class="partitle text3 text4"><p>Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae legendos at vix ad putent delectus delicata usu. 
                    Vidit dissentiet eos cu eum an brute copiosae hendrerit. Eos erant dolorum an. Per</p></div>
        <div class="partitle textbox">Hallo, I’m a student on Computer Science in University of Indonesia.
            I was born in Jakarta , Juny 7th 2000. Currently, I live in Babul Minan Street 007/008 Joglo, Kembangan, West Jakarta. 
            Speaking of my hobby. Playing football is one of my hobby. I can play football since 6th grade.    
            <br><br>
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae legendos at vix ad 
            putent delectus delicata usu. Vidit dissentiet eos cu eum an brute copiosae hendrerit. Eos erant dolorum an. 
            Per facer affert ut. Mei iisque mentitum moderatius cu. Sit munere facilis accusam eu dicat falli consulatu at vis. 
            Te facilisis mnesarchum qui posse mnium mediocritatem est cu. Modus argumentum ne qui tation efficiendi in eos. 
            Ei mea falli legere efficiantur et tollit aliquip debitis mei. 
            <br><br>
            No deserunt mediocritatem mel. 
            Lorem ipsum dolor sit amet et delectus accommodare his consul copiosae legendos at vix ad putent delectus delicata usu. 
            Vidit dissentiet eos cu eum an brute copiosae hendrerit. Eos erant dolorum an. Per facer affert ut. 
            Mei iisque mentitum moderatius cu. Sit munere facilis accusam eu dicat falli consulatu at vis. 
            Te facilisis mnesarchum qui
        </div>
    </div>
    <div class="linestrip color4">
        <div class="linestrip color1 color5"></div>
        <div class="linestrip color2 color6" ></div>
    </div>
    <div class="pict aboutpict">
        <img class="pict" src="{% static 'static2/img/3×4.jpg'%}" alt="">
            <div class="linestrip shadow"></div>
    </div>
    <div class="image2 imageschool">
        <img src="{% static 'static2/img/sekola.jpg'%}" alt="">
            <div class="image2 linetext linetext1"></div>
    </div>
    <div class="card">
        <div class="skill-bar">
            <label>Python</label>
            <div class="container">
                <div class="skill python">70%</div>
            </div>
            <label>Java</label>
            <div class="container">
            <div class="skill java">60%</div>
            </div>
            <label>Microsoft Office</label>
            <div class="container">
            <div class="skill microsoftOffice">80%</div>
            </div>
            <label>Adobe Illustrator</label>
            <div class="container">
            <div class="skill adobeIllustrator">70%</div>
            </div>
            <label>Adobe After Effect</label>
            <div class="container">
            <div class="skill adobeAfter">80%</div>
            </div>
        </div>
    </div>

    <footer class="footer-distributed footerabout">
        <div class="footer-left">
            <h3>My<span>website</span></h3>
            <p class="footer-links">
                <a href="{% url 'lab_2:galery' %}">Gallery</a>
            </p>
            <p class="footer-company-name">Copyright &copy; 2019</p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"><img src="{% static 'static2/img/Gmaps.png'%}" alt=""></i>
                <p><span>Babul Minan Street 007/008</span>Joglo, Kembangan, West Jakarta 11640</p>
            </div>
            <div>
                <i class="fa fa-phone"><img src="{% static 'static2/img/telp.png'%}" alt=""></i>
                <p>+62 858 9469 7220</p>
            </div>
            <div>
                <i class="fa fa-envelope"><img src="{% static 'static2/img/gmail.png'%}" alt=""></i>
                <p><a href="#">fajar245.fa@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>Let's Talk at :</span>
            </p>
            <div class="footer-icons">
                <a href="https://www.facebook.com/jarwof.jarwof" target="_blank"><i class="fa fa-facebook"></i><img src="{% static 'static2/img/facebook.png'%}" alt=""></a>
                <a href="https://twitter.com/Fajar_AS_" target="_blank"><i class="fa fa-twitter"></i><img src="{% static 'static2/img/twitter.png'%}" alt=""></a>
                <a href="https://www.linkedin.com/in/fajar-anugerah-375aa8171/" target="_blank"><i class="fa fa-linkedin"></i><img src="{% static 'static2/img/linkedin.png'%}" alt=""></a>
                <a href="https://www.instagram.com/jwjro_as_/" target="_blank"><i class="fa fa-instagram"></i><img src="{% static 'static2/img/Ig.png'%}" alt=""></a>
            </div>
        </div>
    </footer>
    <script src="{% static 'static2/js/app.js'%}"></script>
</body>
</html>

lab_2/templates/activity.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'static2/css/bootstrap-4.3.1-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <title>Activities</title>
</head>
<body>
    <nav class="navbar">
        <div class="boxx">
            <a href="{% url 'lab_2:hal1' %}"><div id="box2"></div><div id="box">Jr.</div></a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'lab_2:about' %}">About</a></li>
            <li><a href="{% url 'lab_2:project' %}">Project</a></li>
            <li><a href="{% url 'lab_2:activity' %}">Activities</a></li>
            <li><a href="{% url 'lab_2:contact' %}">Contact</a></li>
        </ul>
        <div class="slide">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div class="partitle">
        <div class="partitle partitleloc partitlelocation">Activities</div>
        <div class="linestrip color4"></div>
    </div>
    <div class="rowimage">
        <p><img src="{% static 'static2/img/Act3.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/Act2.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/Act.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/Ens.png'%}" alt=""></p>
    </div>
    <div class="partitle rowtext">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente nulla nemo architecto animi atque reiciendis laboriosam minus, consequatur temporibus incidunt officia facere quibusdam, fuga perferendis voluptatibus nam magni dicta tempora!</p>
        <p class="b">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente nulla nemo architecto animi atque reiciendis laboriosam minus, consequatur temporibus incidunt officia facere quibusdam, fuga perferendis voluptatibus nam magni dicta tempora!</p>
        <p class="c">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente nulla nemo architecto animi atque reiciendis laboriosam minus, consequatur temporibus incidunt officia facere quibusdam, fuga perferendis voluptatibus nam magni dicta tempora!</p>
        <p class="d">Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente nulla nemo architecto animi atque reiciendis laboriosam minus, consequatur temporibus incidunt officia facere quibusdam, fuga perferendis voluptatibus nam magni dicta tempora!</p>
    </div>
    <div class="linevertical"></div>
    <div class="titik"></div>
    <div class="titik titik2"></div>
    <div class="titik titik3"></div>
    <div class="titik titik4"></div>
    <footer class="footer-distributed footerproject">
        <div class="footer-left">
            <h3>My<span>website</span></h3>
            <p class="footer-links">
                <a href="{% url 'lab_2:galery' %}">Gallery</a>
            </p>
            <p class="footer-company-name">Copyright &copy; 2019</p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"><img src="{% static 'static2/img/Gmaps.png'%}" alt=""></i>
                <p><span>Babul Minan Street 007/008</span>Joglo, Kembangan, West Jakarta 11640</p>
            </div>
            <div>
                <i class="fa fa-phone"><img src="{% static 'static2/img/telp.png'%}" alt=""></i>
                <p>+62 858 9469 7220</p>
            </div>
            <div>
                <i class="fa fa-envelope"><img src="{% static 'static2/img/gmail.png'%}" alt=""></i>
                <p><a href="#">fajar245.fa@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>Let's Talk at :</span>
            </p>
            <div class="footer-icons">
                <a href="https://www.facebook.com/jarwof.jarwof" target="_blank"><i class="fa fa-facebook"></i><img src="{% static 'static2/img/facebook.png'%}" alt=""></a>
                <a href="https://twitter.com/Fajar_AS_" target="_blank"><i class="fa fa-twitter"></i><img src="{% static 'static2/img/twitter.png'%}" alt=""></a>
                <a href="https://www.linkedin.com/in/fajar-anugerah-375aa8171/" target="_blank"><i class="fa fa-linkedin"></i><img src="{% static 'static2/img/linkedin.png'%}" alt=""></a>
                <a href="https://www.instagram.com/jwjro_as_/" target="_blank"><i class="fa fa-instagram"></i><img src="{% static 'static2/img/Ig.png'%}" alt=""></a>
            </div>
        </div>
    </footer>
    <script src="{% static 'static2/js/app.js'%}"></script>
    
</body>
</html>

lab_2/templates/contact.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'static2/css/bootstrap-4.3.1-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <title>Contact</title>
</head>
<body>
    <nav class="navbar">
        <div class="boxx">
            <a href="{% url 'lab_2:hal1' %}"><div id="box2"></div><div id="box">Jr.</div></a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'lab_2:hal1' %}">About</a></li>
            <li><a href="{% url 'lab_2:project' %}">Project</a></li>
            <li><a href="{% url 'lab_2:activity' %}">Activities</a></li>
            <li><a href="{% url 'lab_2:contact' %}">Contact</a></li>
        </ul>
        <div class="slide">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div class="partitle">
        <div class="partitle partitleloc partitlelocation">Contact</div>
        <div class="linestrip color4"></div>
    </div>
    <div class="let"><p>LET’S TALK</p></div>
    <div class="socmed">
        <p><img src="{% static 'static2/img/Ig.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/twitter.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/facebook.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/gmail.png'%}" alt=""></p>
        <p><img src="{% static 'static2/img/linkedin.png'%}" alt=""></p>
    </div>
    <div class="partitle socmedtext">
        <p>Jwjro_as_</p>
        <p class="tw">Fajar_as_</p>
        <p class="fb">Fajar Anugerah Subekti</p>
        <p class="gm">Fajar245.fa@gmail.com</p>
        <p class="ld">Fajar Anugerah</p>
    </div>
    <script src="{% static 'static2/js/app.js'%}"></script>
</body>
</html>

lab_2/templates/galery.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'static2/css/bootstrap-4.3.1-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
    <title>Gallery</title>
</head>
<body>
    <nav class="navbar">
        <div class="boxx">
            <a href="{% url 'lab_2:hal1' %}"><div id="box2"></div><div id="box">Jr.</div></a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'lab_2:hal1' %}">About</a></li>
            <li><a href="{% url 'lab_2:project' %}">Project</a></li>
            <li><a href="{% url 'lab_2:activity' %}">Activities</a></li>
            <li><a href="{% url 'lab_2:contact' %}">Contact</a></li>
        </ul>
        <div class="slide">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div><p class="partitle partitleloc partitlelocation">Picture</p></div>
    <div class="row">
        <div class="column">
            <img src="{% static 'static2/img/1.jpg'%}" alt="Snow" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'static2/img/2.jpg'%}" alt="Forest" style="width:100%">
        </div>
        <div class="column">
            <img src="{% static 'static2/img/3.jpg'%}" alt="Mountains" style="width:100%">
        </div>
    </div>
    <script src="{% static 'static2/js/app.js'%}"></script>
</body>
</html>

lab_2/templates/story1.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'static2/css/bootstrap-4.3.1-dist/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'static2/css/style.css'%}">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <title>Fajar Anugerah Subekti</title>
</head>
<body class="bod">
    <nav>
        <div>
            <a href="{% url 'lab_2:hal1' %}"><div id="box2"></div><div id="box">Jr.</div></a>
        </div>
        <ul class="nav-links">
            <li><a href="#about" type="_self">About</a></li>
            <li><a href="#project" type="_self">Project</a></li>
            <li><a href="#activities" type="_self">Activities</a></li>
            <li><a href="{% url 'lab_2:contact' %}"type="_self">Contact</a></li>
        </ul>
        <div class="slide">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <section>
        <div class="container1">
            <img src="{% static 'static2/img/BackGround.png'%}" alt="">
        </div>
    </section>
    <div class="partitle">
        <div class="partitle partitleloc" id="about">About</div>
        <div class="partitle partitleloc partitleloc2 " id="project">Project</div>
        <div class="partitle partitleloc partitleloc3" id="activities">Activities</div>
        <div class="partitle text">“It’s not about ideas. It’s about making ideas happen.”</div>
        <div class="partitle text2">I’m a student on Computer Science in University of Indonesia</div>
        <div class="partitle text3">In Progress to improving the performance of a mechanic at my motorcycle repair shop Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
            Labore quidem eligendi fugiat. Beatae cum tenetur ullam dolore, hic mollitia soluta nihil atque tempora dolorum eius magnam et eum non quae.</div>
    </div>
    <div class="linestrip">
        <div class="linestrip color1"></div>
        <div class="linestrip color2"></div>
        <div class="linestrip color3"></div>
    </div>
    <div class="pict">
        <img class="pict" src="{% static 'static2/img/3×4.jpg'%}" alt="">
            <div class="linestrip shadow"></div>
                <a href="{% url 'lab_2:about' %}" class="pict next nextloc">Read More &raquo;</a>
                <a href="{% url 'lab_2:project' %}" class="pict next nextloc2">Read More &raquo;</a>
                <a href="{% url 'lab_2:activity' %}" class="pict next nextloc3">Read More &raquo;</a>
    </div>
    <div class="image2">
        <img src="{% static 'static2/img/Bengkel.jpg'%}" alt="">
            <div class="image2 linetext"></div>
    </div>
    <div class="image">
        
        <img src="{% static 'static2/img/Act.jpg'%}" alt="">
        <img id="size2" src="{% static 'static2/img/Act2.jpg'%}" alt="">
        <h3>Computer Science League 2019</h3>
        <h3 id="righth3">Runtime Error</h3>
        <h4>Futsal Competition at faculty of Computer Science are regularly held every year</h4>
        <h4 id="righth4">Running competition activities on 2019 at faculty of Computer Science</h4>
    </div>

    <footer class="footer-distributed">
        <div class="footer-left">
            <h3>My<span>website</span></h3>
            <p class="footer-links">
                <a href="{% url 'lab_2:galery' %}">Gallery</a>
            </p>
            <p class="footer-company-name">Copyright &copy; 2019</p>
        </div>
        <div class="footer-center">
            <div>
                <i class="fa fa-map-marker"><img src="{% static 'static2/img/Gmaps.png'%}" alt=""></i>
                <p><span>Babul Minan Street 007/008</span>Joglo, Kembangan, West Jakarta 11640</p>
            </div>
            <div>
                <i class="fa fa-phone"><img src="{% static 'static2/img/telp.png'%}" alt=""></i>
                <p>+62 858 9469 7220</p>
            </div>
            <div>
                <i class="fa fa-envelope"><img src="{% static 'static2/img/gmail.png'%}" alt=""></i>
                <p><a href="#">fajar245.fa@gmail.com</a></p>
            </div>
        </div>
        <div class="footer-right">
            <p class="footer-company-about">
                <span>Let's Talk at :</span>
            </p>
            <div class="footer-icons">
                <a href="https://www.facebook.com/jarwof.jarwof" target="_blank"><i class="fa fa-facebook"></i><img src="{% static 'static2/img/facebook.png'%}" alt=""></a>
                <a href="https://twitter.com/Fajar_AS_" target="_blank"><i class="fa fa-twitter"></i><img src="{% static 'static2/img/twitter.png'%}" alt=""></a>
                <a href="https://www.linkedin.com/in/fajar-anugerah-375aa8171/" target="_blank"><i class="fa fa-linkedin"></i><img src="{% static 'static2/img/linkedin.png'%}" alt=""></a>
                <a href="https://www.instagram.com/jwjro_as_/" target="_blank"><i class="fa fa-instagram"></i><img src="{% static 'static2/img/Ig.png'%}" alt=""></a>
            </div>
        </div>
    </footer>
    <script src="{% static 'static2/js/app.js'%}"></script>
</body> 
</html> 